apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - infrastructure/cert-manager.yaml
  - infrastructure/cinder-csi.yaml
  - infrastructure/cloud-controller-manager.yaml
  - infrastructure/ingress-nginx.yaml
  - infrastructure/weave-gitops.yaml
